name: sms_sync_mobile
description: 短信同步应用 - 将手机短信同步到电脑
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.1
  web_socket_channel: ^3.0.3
  shared_preferences: ^2.5.4
  device_info_plus: ^12.3.0
  permission_handler: ^12.0.1
  android_intent_plus: ^6.0.0
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  flutter_background_service_android:
    path: third_party/flutter_background_service_android

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "../mobile_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
